name: calendar_parser_acs
description: Calendar App with Parser for ACS Students

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  http: ^0.13.4
  built_value: ^8.3.0
  built_collection: ^5.1.1
  redux: ^5.0.0
  flutter_redux: ^0.9.0
  redux_epics: ^0.15.1
  freezed_annotation: ^2.0.3
  table_calendar: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  built_value_generator: ^8.3.0
  freezed: ^2.0.3

dependency_overrides:
  rxdart: ^0.27.3
  analyzer: ^4.0.0
  meta: ^1.7.0

flutter:

  uses-material-design: true
